local L = LibStub("AceLocale-3.0"):NewLocale("WorldBossStatus", "deDE")

if not L then
	return
end

L["Automatically track holiday bosses during world events."] = "Saison Bosse automatisch verfolgen während eines Weltevents."
L["Available"] = "Verfügbar"
L["Bonus Roll Options"] = "Bonuswurf Einstellungen"
L["Bonus Rolls"] = "Bonus Würfe"
L["Bosses"] = "Bosse"
L["Boss Options"] = "Boss Einstellungen"
L["Character"] = "Charakter"
L["Character Options"] = "Charakter Optionen"
L["Characters"] = "Charakter"
L["Click to open the options menu"] = "Klicken um das Einstellungsmenu zu öffnen"
L["Click to remove the selected tracked character."] = "Klicke um den anzuzeigenden Charakter zu entfernen."
L["Defeated"] = "Besiegt"
L["Enable"] = "Aktivieren"
L["Enable hiding inactive characters."] = "Aktiviere inaktive Charakter verstecken."
L["Enable level restriction."] = "Aktiviere Stufen Beschränkung"
L["General Options"] = "Allgemeine Einstellungen"
L["Hide characters that have been inactive for this many days."] = "Verstecke Charaktere die so viele Tage inaktiv gewesen sind."
L["Hide Inactive Characters"] = "Verstecke inaktive Charakter"
L["Inactivity Threshold (days)"] = "Inaktivitätszeitraum (Tage)"
L["Level Restriction"] = "Stufen Beschränkung"
L["Minimap Button"] = "Minikarten Schaltfläche"
L["Minimum Level"] = "Minimum Level"
L["On this account"] = "Auf diesem Account"
L["On this realm"] = "Auf diesem Realm"
L["Realm"] = "Realm"
L["Remove"] = "Entfernen"
L["Remove Tracked Characters"] = "Entferne anzuzeigende Charakter"
L["Select a realm to remove a tracked character from."] = "Wähle einen Realm von dem ein anzuzeigender Charakter entfernt werden soll."
L["Select the currencies you would like to track."] = "Wähle welche Währung angezeigt werden soll."
L["Select the tracked character to remove."] = "Wähle den anzuzeigenden Charakter zum entfernen."
L["Select the world bosses you would like to track."] = "Wähle welcher Weltboss angezeigt werden soll."
L["Show Characters"] = "Zeige Charakter"
L["Show characters on this realm."] = "Zeige Charakter auf diesem Realm."
L["Show characters on this WoW account."] = "Zeige Charakter auf diesem WoW Account."
L["Show characters this level and higher."] = "Zeige Charakter dieses Levels oder höher."
L["The Celestials"] = "Die vier Himmlischen Erhabenen"
L["Toggles the display of the minimap button."] = "An/Aus der Minikarten Schaltfläche."
L["Toggles the display of this world boss."] = "An/Ausschalten dieses Weltbosses."
L["Tracked Bosses"] = "Anzuzeigende Bosse"
L["Tracked Currencies"] = "Währungen anzeigen"
L["Track holiday bosses"] = "Saison Bosse verfolgen"
L["Undefeated"] = "Unbesiegt"
L["World Bosses"] = "Weltbosse"
L["World Boss Status"] = "Weltboss Status"
