local L = LibStub("AceLocale-3.0"):NewLocale("WorldBossStatus", "itIT")

if not L then
	return
end

L["Automatically track holiday bosses during world events."] = "Evidenzia automaticamente il boss dell'evento mondiale attivo"
L["Available"] = "Disponibile"
L["Bonus Roll Options"] = "Opzioni scommessa"
L["Bonus Rolls"] = "Scommesse"
L["Bosses"] = "Boss"
L["Boss Options"] = "Opzioni Boss"
L["Character"] = "Personaggio"
L["Character Options"] = "Opzioni personaggio"
L["Characters"] = "Personaggi"
L["Click to open the options menu"] = "Clicca per aprire il menù delle opzioni"
L["Click to remove the selected tracked character."] = "Clicca per rimuovere dall'elenco il personaggio selezionato"
L["Defeated"] = "Sconfitto"
L["Enable"] = "Abilita"
L["Enable hiding inactive characters."] = "Nascondere i personaggi inattivi?"
L["Enable level restriction."] = "Abilita limiti di livello"
L["General Options"] = "Opzioni generali"
L["Hide characters that have been inactive for this many days."] = "Nascondi personaggi inattivi da questo numero di giorni"
L["Hide Inactive Characters"] = "Nascondi personaggi inattivi"
L["Inactivity Threshold (days)"] = "Inattivi da almeno (giorni)"
L["Level Restriction"] = "Limiti di livello"
L["Minimap Button"] = "Pulsante minimappa"
L["Minimum Level"] = "Livello minimo"
L["On this account"] = "Di questo account"
L["On this realm"] = "Su questo reame"
L["Realm"] = "Reame"
L["Remove"] = "Nascondi"
L["Remove Tracked Characters"] = "Non seguire più personaggi"
L["Select a realm to remove a tracked character from."] = "Scegli reame dal cui elenco rimuovere personaggi"
L["Select the currencies you would like to track."] = "Scegli le valute da mostrare"
L["Select the tracked character to remove."] = "Scegli personaggio da rimuovere dall'elenco"
L["Select the world bosses you would like to track."] = "Scegli i boss da mostrare"
L["Show Characters"] = "Mostra personaggi"
L["Show characters on this realm."] = "Mostra personaggi su questo reame"
L["Show characters on this WoW account."] = "Mostra personaggi di questo account"
L["Show characters this level and higher."] = "Mostra personaggi da questo livello in su"
L["The Celestials"] = "I Celestiali"
L["Toggles the display of the minimap button."] = "Mostra/nascondi il pulsante sulla minimappa"
L["Toggles the display of this world boss."] = "Mostra/nascondi questo boss"
L["Tracked Bosses"] = "Boss selezionati"
L["Tracked Currencies"] = "Valute in evidenza"
L["Track holiday bosses"] = "Boss dell'Evento"
L["Undefeated"] = "Disponibile"
L["World Bosses"] = "Boss mondiali"
L["World Boss Status"] = "World Boss Status"
