local L = LibStub("AceLocale-3.0"):NewLocale("WorldBossStatus", "ruRU")

if not L then
	return
end

L["Available"] = "Доступен" -- Needs review
L["Bonus Roll Options"] = "Настройки бонусного броска"
L["Bonus Rolls"] = "Бонусный бросок"
L["Bosses"] = "Боссы"
L["Boss Options"] = "Настройки Боссов"
L["Character"] = "Персонаж"
L["Character Options"] = "Настройки персонажа"
L["Characters"] = "Персонажи"
L["Click to open the options menu"] = "Щелкните чтобы открыть меню настроек"
L["Click to remove the selected tracked character."] = "Нажмите для удаления выбранных отслеживаемых персонажей"
L["Defeated"] = "Убит"
L["Enable"] = "Включить"
L["Enable hiding inactive characters."] = "Включить прятание неактивных персонажей"
L["Enable level restriction."] = "Включить уровень допуска"
L["General Options"] = "Общие настройки"
L["Hide characters that have been inactive for this many days."] = "Прятать персонажей которые были неактивны во время нескольких дней"
L["Hide Inactive Characters"] = "Спрятать неактивных персонажей"
L["Inactivity Threshold (days)"] = "Время бездействия (дней)"
L["Level Restriction"] = "Уровень допуска"
L["Minimap Button"] = "Кнопка у миникарты"
L["Minimum Level"] = "Минимальный уровень"
L["On this account"] = "На этом аккаунте"
L["On this realm"] = "В этом мире"
L["Realm"] = "Мир"
L["Remove"] = "Удалить"
L["Remove Tracked Characters"] = "Удалить отслеживаемых персонажей"
L["Select a realm to remove a tracked character from."] = "Выберите мир для удаления отслеживаемых персонажей"
L["Select the currencies you would like to track."] = "Выберите валюту, которую хотите отслеживать"
L["Select the tracked character to remove."] = "Выберите отслеживаемых персонажей для удаления"
L["Select the world bosses you would like to track."] = "Выберите мировых боссов, которых хотите отслеживать"
L["Show Characters"] = "Показ персонажей"
L["Show characters on this realm."] = "Показ персонажей из этого мира"
L["Show characters on this WoW account."] = "Показ персонажей этого аккаунта"
L["Show characters this level and higher."] = "Показывать персонажей этого уровня и выше"
L["The Celestials"] = "Четырe небожителя"
L["Toggles the display of the minimap button."] = "Отображение кнопки у миникарты"
L["Toggles the display of this world boss."] = "Отображать этого мирового босса"
L["Tracked Bosses"] = "Отслеживаемые Боссы"
L["Tracked Currencies"] = "Отслеживать валюту"
L["Undefeated"] = "Не убит"
L["World Bosses"] = "Мировые Боссы"
L["World Boss Status"] = "Статус Мировых Боссов"
